apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fb3w56e8t-go
  janus-idp.io/tekton: fb3w56e8t-go
  backstage.io/kubernetes-id: fb3w56e8t-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fb3w56e8t-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
