apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fb3w56e8t-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fb3w56e8t-go 
  name: fb3w56e8t-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fb3w56e8t-go 
